version: '3'
services:
  go-so-trends:
    container_name: go-so-trends-app
    build: .
    ports:
      - 8080:8080
    environment:
      - HOST=0.0.0.0
      - PORT=8080
  neo4j:
    container_name: neo4j
    image: neo4j:latest
    ports:
      - 7474:7474
      - 7687:7687
    environment:
      - NEO4J_AUTH=neo4j/${NEO4J_PASSWORD}
      # - NEO4J_server_memory_heap_initial__size=6G
      - NEO4J_server_memory_heap_max__size=6G
      # - NEO4J_apoc_export_file_enabled=true
      # - NEO4J_apoc_import_file_enabled=true
      # - NEO4J_apoc_import_file_use__neo4j__config=true
      # - NEO4J_PLUGINS=["apoc", "graph-data-science"]
    volumes:
      - ./neo4j_db/data:/data
      - ./neo4j_db/logs:/logs
      - ./neo4j_db/import:/var/lib/neo4j/import
      - ./neo4j_db/plugins:/plugins